In [ ]:
# Reading weights and biases from a onnx model file

In [1]:
import onnx
import numpy as np
import re

In [2]:
model = onnx.load("/home/metal/dev/vaaman-cnn/onnx/vgg16-12.onnx")
graph_def = model.graph
initializers = graph_def.initializer

In [3]:
model2 = onnx.load('/home/metal/dev/vaaman-cnn/onnx/vgg16-12-int8.onnx')
graph_def2 = model2.graph
initializers2 = graph_def2.initializer

In [4]:
for initializer in initializers2:
    if ((initializer.name) == "vgg0_conv3_weight_quantized"):
        print(initializer.name)
        print(initializer.dims)
        #array = np.array(initializer.float_data).reshape(initializer.dims)
        array = np.frombuffer(initializer.raw_data, dtype=np.uint8).reshape(initializer.dims)
        print(array[0,0,:,:])
        print(array[0,1,:,:])
        print(array[0,2,:,:])
        print()

vgg0_conv3_weight_quantized
[128, 128, 3, 3]
[[  2  58 250]
 [228   6  42]
 [238 215  24]]
[[255 242 238]
 [  3 248 254]
 [  1   2 244]]
[[255 246 248]
 [  0   1 251]
 [248   7   6]]



In [5]:
print(f"These many params: 14 710 464 conv parameters")

These many params: 14 710 464 conv parameters


In [1]:
# Describe
p = re.compile("vgg0_conv[0-9]+_bias")
for initializer in initializers:
    if (p.match(initializer.name)):
        print(initializer.name)
        print(initializer.dims)
        print(initializer.raw_data)

NameError: name 're' is not defined