In [ ]:
# Reading weights and biases from a onnx model file

In [1]:
import onnx
import numpy as np
import re
import math

In [2]:
model = onnx.load("/home/metal/dev/vaaman-cnn/onnx/vgg16-12-int8.onnx")
graph_def = model.graph
initializers = graph_def.initializer

In [10]:
model2 = onnx.load('/home/metal/dev/vaaman-cnn/onnx/resnet50-v2-7.onnx')
graph_def2 = model2.graph
initializers2 = graph_def2.initializer

In [ ]:
for node in graph_def.node:
    # node inputs
    for idx, node_input_name in enumerate(node.input):
        print(idx, node_input_name)
    # node outputs
    #for idx, node_output_name in enumerate(node.output):
    #    print(idx, node_output_name)

In [ ]:
for initializer in initializers2:
    print(initializer.name)
    print(initializer.dims)
    #if ((initializer.name) == "vgg0_conv3_weight_quantized"):
    #    print(initializer.name)
    #    print(initializer.dims)
    #    #array = np.array(initializer.float_data).reshape(initializer.dims)
    #    array = np.frombuffer(initializer.raw_data, dtype=np.uint8).reshape(initializer.dims)
    #    print(array[0,0,:,:])
    #    print(array[0,1,:,:])
    #    print(array[0,2,:,:])
    #    print()
        

In [ ]:
p = re.compile("batch")
for initializer in initializers2:
    print(initializer.name)
    #if (p.match(initializer.name)):
    #    print(initializer.name)
    #    print(initializer.dims)
    #    print(onnx.TensorProto.INT32)
    #    print(initializer.int32_data)

In [5]:
print(f"These many params: 14 710 464 conv parameters")

These many params: 14 710 464 conv parameters


In [14]:
def fetch_kernel(layer, n, c):
    lname = 'vgg0_conv{}_weight_quantized'.format(layer)
    for initializer in initializers:    
        if ((initializer.name) == lname):
            array = np.frombuffer(initializer.raw_data, dtype=np.uint8).reshape(initializer.dims)
            return array[n,c,:,:]
fetch_kernel(12, 0, 1)

array([[215, 219, 236],
       [206, 219, 233],
       [207, 206, 217]], dtype=uint8)

In [4]:
for initializer in initializers:
    #print(initializer.name)
    #print(initializer.dims)
    if ((initializer.name) == "vgg0_conv0_weight_quantized"):
    #    print(initializer.name)
    #    print(initializer.dims)
    #    array = np.array(initializer.float_data).reshape(initializer.dims)
        array = np.frombuffer(initializer.raw_data, dtype=np.uint8).reshape(initializer.dims)
        print(array[0,0,:,:])
        print(array[0,1,:,:])
        print(array[0,2,:,:])
        print()
        

[[ 78  50   6]
 [ 56  15 247]
 [ 23   5 247]]
[[211 174 208]
 [195 129 193]
 [244 225   7]]
[[ 28  21  28]
 [ 26 247  29]
 [ 37  52  63]]

